import type { Locale } from "@tnajem/shared";

/* Tnajem i18n — COMPLETE dictionary for all MVP screens.
   Agents: READ keys from here (t.<ns>.<key>); do NOT edit this file to avoid collisions.
   Student-facing Arabic is Derja. `ar` is typed `typeof fr` so both stay in sync. */

const fr = {
  common: {
    appName: "Tnajem",
    free1st: "1ère gratuite",
    /* Pluralised, and "Complet" at 0 — the old `${n} places` rendered "1 places"
       and, worse, "0 places" on a full class, which reads as still-bookable. */
    seats: (n: number) =>
      n <= 0 ? "Complet" : n === 1 ? "1 place restante" : `${n} places restantes`,
    seeAll: "Tout voir",
    copy: "Copier",
    copied: "Copié ✓",
    share: "Partager",
    back: "Retour",
    next: "Suivant",
    publish: "Publier",
    save: "Enregistrer",
    cancel: "Annuler",
    tnd: "TND",
    min: "min",
    loading: "Chargement…",
    demoMode: "Mode démo — aucune base connectée (données d'exemple).",
  },
  nav: { classes: "Cours", explore: "Explorer", messages: "Messages", profile: "Profil", dashboard: "Tableau de bord", students: "Élèves", earnings: "Revenus" },
  /* WCAG 2.4.1 Bypass Blocks. Every screen has a sticky header with navigation,
     so without this a keyboard or screen-reader user tabs the whole nav on every
     single route before reaching the content. */
  skipToContent: "Aller au contenu",
  home: {
    badge: "MVP · Tnajem",
    title: "Tnajem",
    tagline: "Ton prof, en direct. Réserve, apprends, réussis.",
    seeStore: "Voir une vitrine",
    becomeTutor: "Créer ma page de prof",
    forStudents: "Je suis élève",
  },
  onboarding: {
    step: (a: number, b: number) => `Étape ${a}/${b}`,
    title: "Crée ta page en 2 minutes",
    lead: "Pas de site, pas de frais. Juste ton nom, ta matière — et tu peux déjà encaisser.",
    name: "Ton nom de prof",
    namePh: "ex. Yassine Khelifi",
    subject: "Ta matière & niveau",
    subjectPh: "ex. Maths — collège, lycée, Bac",
    bio: "Une phrase sur toi (en darija, c'est parfait)",
    bioPh: "ex. On révise les maths, du collège au Bac, à ton rythme.",
    link: "Ton lien Tnajem",
    preview: "Aperçu en direct",
    cta: "Publier ma page",
    /* This once named a commission rate as if it were being charged. It is not:
       during the pilot Tnajem takes no commission and holds no money. Future
       pricing belongs on /tarifs, where it is labelled as future — never here,
       stated as a live deduction. */
    fine: "Gratuit. Pendant le pilote, Tnajem ne prend aucune commission — tu gardes 100 %.",
    done: "Ta page est en ligne 🎉",
  },
  storefront: {
    /* `bookedThisWeek: "Réservé 23 fois cette semaine"` deleted: a hardcoded,
       fabricated number on a platform that has taken zero bookings. */
    live: "Cours en direct",
    packs: "Fiches & enregistrements",
    cta: "Réserver — 1ère séance gratuite",
    reviews: "avis",
    about: "À propos",
  },
  classDetail: { with: "avec", about: "Description", when: "Quand", price: "Prix", book: "Réserver cette séance", freeFirst: "1ère séance gratuite" },
  /* Payments are OFF (lib/payments.ts). Nothing here may promise a charge:
     "Confirmer & payer" / "Payer X TND" / "Aucun débit" all implied Tnajem takes
     the money. It does not — the student settles with the tutor directly. */
  checkout: {
    title: "Confirmer ta réservation",
    nextSessions: "Séances suivantes",
    okTitle: "C'est réservé !",
    okBody: "Ta place est confirmée. On t'envoie le lien sur WhatsApp.",
    okCta: "Voir mes cours",
    errAuth: "Connecte-toi pour réserver ta place.",
    errFull: "Plus de places pour cette séance.",
    errGeneric: "La réservation n'a pas marché. Réessaie.",
  },
  dashboard: {
    hi: (name: string) => `Salut, ${name} 👋`,
    online: "Ta page est en ligne.",
    monthGood: "Ce mois-ci · ça monte bien.",
    balance: "Solde disponible",
    emptyNote: "Pas encore de revenus — ça commence avec ton premier élève.",
    shareTitle: "Partage ton lien, remplis tes cours",
    shareBody: "Ton lien, c'est ta vitrine. Poste-le sur TikTok, Insta ou ton groupe WhatsApp. Chaque élève qui clique voit tes séances, tes tarifs et tes avis.",
    shareBtn: "Partager mon lien",
    how: "Comment ça marche",
    s1t: "Partage ton lien", s1p: "À tes élèves actuels et à ton audience.",
    /* These once described an online checkout and a revenue split. Payments are
       off, so the pilot split is 100/0 and no rail exists to name. */
    s2t: "Tes élèves réservent", s2p: "Tu vois leur prénom et leur réservation dans ton tableau de bord.",
    trend: (p: number) => `+${p}% vs le mois dernier`,
    cashout: "Retirer vers Flouci",
    recent: "Activité récente",
    newClass: "Créer une classe",
    newPack: "Ajouter des fiches",
    stStudents: "élèves", stSessions: "séances", stRating: "note",
    viewStore: "Voir ma vitrine",
    myClasses: "Mes cours",
    myPacks: "Mes fiches",
    createStore: "Crée ta vitrine",
    createStoreBody: "Publie ta page de prof — ça prend 2 minutes. Ensuite tu partages ton lien et tu crées tes cours.",
  },
  createClass: {
    title: "Créer une classe en direct",
    name: "Titre", namePh: "ex. Intégrales — révision express",
    desc: "Description (optionnel)",
    date: "Date & heure", duration: "Durée (min)", price: "Prix (TND)", seats: "Places",
    freeFirst: "Offrir la 1ère séance gratuitement", create: "Publier la classe",
  },
  createPack: { title: "Ajouter des fiches / enregistrement", name: "Titre", meta: "Détail (ex. 42 pages · 6 vidéos)", price: "Prix (TND)", create: "Publier" },
  /* Only the four keys /dashboard/payout actually renders. The withdrawal-form
     strings (to/amount/request) and the timing promises ("Les retraits arrivent
     sous 1–3 jours.") were deleted: no payout rail exists (lib/payments.ts
     throws), so nothing may state when money would arrive. */
  payout: { title: "Retirer mes gains", available: "Disponible", wallet: "Portefeuille Flouci", bank: "Compte bancaire (RIB)" },
  student: {
    title: "Mes cours", soon: "DÉMARRE BIENTÔT", with: "avec",
    hours: "heures", mins: "min", secs: "sec",
    join: "Rejoindre le direct", past: "Séances passées", replay: "Revoir",
    empty: "Pas encore de cours — explore les profs pour commencer.",
  },
  live: {
    tag: "EN DIRECT DANS", with: "avec", waiting: (n: number) => `${n} élèves déjà connectés`,
    note: "Ta caméra est optionnelle — tu peux suivre en silence et écrire dans le chat.", join: "Entrer dans la classe",
  },
  auth: {
    title: "Connexion", phone: "Numéro de téléphone", phonePh: "+216 ...",
    sendCode: "Recevoir le code", code: "Code reçu par SMS", verify: "Vérifier",
    asTutor: "Je suis prof", asStudent: "Je suis élève / parent",
    /* Was our SMS-provider release note, shown verbatim to every visitor. */
    pending: "Entre ton numéro : on t'envoie un code par SMS. Pas de mot de passe.",
  },
  consent: {
    title: "Accord du parent / tuteur",
    body: "Pour un élève de moins de 18 ans, la loi tunisienne (INPDP) exige l'accord d'un parent ou tuteur. Renseigne ses informations pour activer le compte.",
    gName: "Nom du parent / tuteur", // phase-a lane L5 (A18.2): gPhone removed — the phone is no longer asked for
    gEmail: "E-mail du parent / tuteur",
    /* Says WHY the address is asked for. Without this the field reads as one
       more thing to hand over; with it, it is the parent's own account. */
    gEmailHelp:
      "C'est avec cette adresse que le parent se connecte à son propre compte, pour voir les séances réservées et lire les conversations de son enfant.",
    errGEmail: "Cette adresse e-mail n'est pas valide.",
    errGSelf: "Utilise l'adresse du parent, pas la tienne.",
    submit: "Activer le compte",
    // phase-a lane L5 (A18.1): the child no longer declares to be the parent — the
    // old `agree` tick was a false statement on a legal record, and was never
    // even sent to the server.
    // LEGAL-REVIEW: consent wording. The parent-side e-mail confirmation is Dm3
    // (Phase D). This line is shown only while ALLOW_MINORS=1, which stays off
    // until Dm3 exists.
    info: "Ton parent recevra un e-mail pour confirmer.",
  },
  account: { title: "Mon profil", language: "Langue", logout: "Se déconnecter", role: "Rôle", help: "Aide & support (WhatsApp)" },
  // phase-a lane L5 (A18.13): role NAMES for /account — never the sign-up button text.
  roles: { student: "Élève", tutor: "Prof", guardian: "Parent", admin: "Admin" },
  verif: {
    badge: "Vérifié",
    draftTitle: "Vérifie ton compte pour passer en ligne",
    draftBody: "Ta page n'est pas encore visible. Ajoute ta pièce d'identité (diplômes optionnels) pour être vérifié et listé dans Explorer.",
    draftCta: "Vérifier mon compte",
    pendingTitle: "Vérification en cours",
    pendingBody: "On vérifie tes documents. Ta page passe en ligne dès l'approbation (souvent 24–48h).",
    rejectedTitle: "Vérification refusée",
    rejectedBody: "Un souci avec tes documents — corrige et renvoie.",
    rejectedCta: "Renvoyer mes documents",
    verifiedTitle: "Compte vérifié ✓",
    verifiedBody: "Ta page est en ligne et listée dans Explorer.",
  },
  tools: {
    section: "Outils du cours",
    join: "Rejoindre la vidéo",
    whiteboard: "Tableau blanc",
    quiz: "Lancer le quiz",
    replay: "Revoir l'enregistrement",
    none: "Aucun outil ajouté pour cette séance.",
    setLinks: "Outils du cours (optionnel)",
    videoUrl: "Lien vidéo (Jitsi / Meet)",
    whiteboardUrl: "Lien tableau blanc (Bitpaper / Excalidraw)",
    quizUrl: "Lien quiz (Wooclap / Quizizz)",
    hint: "Colle tes liens — tes élèves les ouvrent en un tap pendant le cours.",
  },
  extra: {
    error: "Une erreur s'est produite.",
    settings: "Réglages",
    notifications: "Notifications",
    classPublished: "Classe publiée ✓",
    packPublished: "Fiches publiées ✓",
    modeEarning: "Avec gains",
    modeEmpty: "Nouveau prof",
    demoPreview: "Aperçu démo",
    searchPh: "Cherche un prof ou une matière…",
    featured: "Profs vérifiés",
    noResults: "Aucun prof trouvé",
    allSubjects: "Tous",
    comingSoon: "Bientôt disponible",
  },
  footer: {
    product: "Produit",
    legal: "Légal",
    help: "Aide",
    terms: "Conditions d'utilisation",
    privacy: "Politique de confidentialité",
    contact: "Contact",
    tagline: "Le lien entre les élèves tunisiens et leurs profs.",
    rights: (y: number) => `© ${y} Tnajem · Tunisie`,
  },
  err: {
    nfCode: "404",
    nfTitle: "Cette page n'existe pas",
    nfBody: "Le lien est peut-être erroné, ou la page a été retirée. Reviens à l'accueil ou cherche un prof.",
    nfHome: "Retour à l'accueil",
    nfExplore: "Trouver un prof",
    crashTitle: "Quelque chose a cassé",
    crashBody: "Une erreur inattendue s'est produite de notre côté. Réessaie — si ça continue, écris-nous.",
    retry: "Réessayer",
    home: "Aller à l'accueil",
    ref: "Référence",
  },
};

const ar: typeof fr = {
  common: {
    appName: "تنجّم",
    free1st: "الأولى فابور",
    seats: (n: number) =>
      n <= 0 ? "كامل" : n === 1 ? "بلاصة وحدة تبقات" : n === 2 ? "زوز بلايص تبقاو" : `${n} بلايص تبقاو`,
    seeAll: "شوف الكل",
    copy: "انسخ",
    copied: "تنسخ ✓",
    share: "شارك",
    back: "ارجع",
    next: "كمّل",
    publish: "انشر",
    save: "سجّل",
    cancel: "إلغاء",
    tnd: "د.ت",
    min: "دقيقة",
    loading: "قاعد يحمّل…",
    demoMode: "وضع تجريبي — ما فماش قاعدة موصولة (بيانات أمثلة).",
  },
  nav: { classes: "حصص", explore: "اكتشف", messages: "رسائل", profile: "حسابي", dashboard: "لوحتي", students: "تلاميذ", earnings: "أرباح" },
  skipToContent: "امشي للمحتوى",
  home: {
    badge: "MVP · تنجّم",
    title: "تنجّم",
    tagline: "أستاذك دايركت. احجز، اقرا، انجح.",
    seeStore: "شوف واجهة أستاذ",
    becomeTutor: "اعمل صفحتي كأستاذ",
    forStudents: "أنا تلميذ",
  },
  onboarding: {
    step: (a: number, b: number) => `مرحلة ${a}/${b}`,
    title: "اعمل صفحتك في دقيقتين",
    lead: "بلا موقع، بلا مصاريف. كان اسمك ومادتك — وتنجم تقبض.",
    name: "اسمك كأستاذ",
    namePh: "مثال: ياسين خليفي",
    subject: "مادتك والمستوى",
    subjectPh: "مثال: رياضيات — باكالوريا",
    bio: "جملة عليك (بالدارجة، باهي)",
    bioPh: "مثال: نراجعو رياضيات الباك على راحتك.",
    link: "اللينك متاعك في تنجّم",
    preview: "كيفاش باش تبان",
    cta: "انشر صفحتي",
    fine: "مجاني. في فترة التجربة، تنجّم ما تاخذ حتى عمولة — تحتفظ بـ 100 %.",
    done: "صفحتك على الخط 🎉",
  },
  storefront: {
    live: "حصص دايركت",
    packs: "ملخصات وتسجيلات",
    cta: "احجز — أول حصة فابور",
    reviews: "تقييم",
    about: "نبذة",
  },
  classDetail: { with: "مع", about: "الوصف", when: "الوقت", price: "الثمن", book: "احجز الحصة هاذي", freeFirst: "أول حصة فابور" },
  checkout: {
    title: "أكّد حجزك",
    nextSessions: "الحصص الجاية",
    okTitle: "حجزت بلاصتك!",
    okBody: "مكانك مؤكّد. نبعثولك الرابط على واتساب.",
    okCta: "شوف حصصي",
    errAuth: "ادخل لحسابك باش تحجز بلاصتك.",
    errFull: "ما عادش فما بلايص في الحصة هاذي.",
    errGeneric: "الحجز ما مشاش. عاود حاول.",
  },
  dashboard: {
    hi: (name: string) => `أهلا ${name} 👋`,
    online: "صفحتك على الخط.",
    monthGood: "هذا الشهر · تمشي مليح.",
    balance: "الرصيد المتوفّر",
    emptyNote: "ما زال ما عندكش مداخيل — تبدا مع أول تلميذ.",
    shareTitle: "شارك اللينك متاعك، عمّر حصصك",
    shareBody: "اللينك متاعك هو واجهتك. انشرو في تيك توك، انستا ولا قروب الواتساب. كل تلميذ يكليكي عليه يشوف حصصك، أسوامك والآراء.",
    shareBtn: "شارك اللينك متاعي",
    how: "كيفاش يخدم",
    s1t: "شارك اللينك متاعك", s1p: "لتلامذتك توّا وللناس اللي يتبعوك.",
    s2t: "تلاميذك يحجزو", s2p: "تشوف إسمهم الأول والحجز متاعهم في لوحتك.",
    trend: (p: number) => `+${p}% مقارنة بالشهر الفارط`,
    cashout: "اسحب لفلوسي",
    recent: "النشاط الأخير",
    newClass: "اعمل حصة",
    newPack: "زيد ملخصات",
    stStudents: "تلميذ", stSessions: "حصة", stRating: "تقييم",
    viewStore: "شوف واجهتي",
    myClasses: "حصصي",
    myPacks: "ملخصاتي",
    createStore: "اعمل واجهتك",
    createStoreBody: "انشر صفحتك كأستاذ — تاخذ دقيقتين. من بعد تشارك اللينك متاعك وتعمل حصصك.",
  },
  createClass: {
    title: "اعمل حصة دايركت",
    name: "العنوان", namePh: "مثال: التكامل — مراجعة سريعة",
    desc: "الوصف (اختياري)",
    date: "النهار والوقت", duration: "المدة (دقيقة)", price: "الثمن (د.ت)", seats: "البلايص",
    freeFirst: "أعطي أول حصة فابور", create: "انشر الحصة",
  },
  createPack: { title: "زيد ملخصات / تسجيل", name: "العنوان", meta: "تفاصيل (مثال: 42 صفحة · 6 فيديوهات)", price: "الثمن (د.ت)", create: "انشر" },
  payout: { title: "اسحب أرباحي", available: "المتوفّر", wallet: "محفظة فلوسي", bank: "حساب بنكي (RIB)" },
  student: {
    title: "حصصي", soon: "تبدا قريب", with: "مع",
    hours: "ساعات", mins: "دقيقة", secs: "ثانية",
    join: "ادخل للدايركت", past: "حصص فاتت", replay: "عاود شوف",
    empty: "ما زال ما عندكش حصص — اكتشف الأساتذة باش تبدا.",
  },
  live: {
    tag: "الدايركت يبدا في", with: "مع", waiting: (n: number) => `${n} تلامذة متّصلين`,
    note: "الكاميرا اختيارية — تنجم تتابع بصمت وتكتب في الدردشة.", join: "ادخل للحصة",
  },
  auth: {
    title: "الدخول", phone: "نمرة التليفون", phonePh: "+216 ...",
    sendCode: "ابعث الكود", code: "الكود اللي جاك بالـSMS", verify: "أكّد",
    asTutor: "أنا أستاذ", asStudent: "أنا تلميذ / ولي",
    pending: "حطّ نمرتك : نبعثولك كود بالـSMS. بلا كلمة سرّ.",
  },
  consent: {
    title: "موافقة الولي",
    body: "للتلميذ تحت 18 سنة، القانون التونسي (INPDP) يستوجب موافقة الولي. عمّر معلوماته باش يتفعّل الحساب.",
    gName: "اسم الولي", // phase-a lane L5 (A18.2): gPhone removed
    gEmail: "إيميل الولي",
    gEmailHelp:
      "بالإيميل هذا الولي يدخل للحساب متاعو، باش يشوف الحصص المحجوزة ويقرا محادثات ولدو.",
    errGEmail: "الإيميل هذا موش صحيح.",
    errGSelf: "استعمل إيميل الولي، موش متاعك.",
    submit: "فعّل الحساب",
    // phase-a lane L5 (A18.1) — LEGAL-REVIEW: consent wording (see fr.consent.info).
    info: "وليّك باش يوصلو إيميل باش يأكّد.",
  },
  account: { title: "حسابي", language: "اللغة", logout: "تسجيل الخروج", role: "الدور", help: "مساعدة (واتساب)" },
  // phase-a lane L5 (A18.13)
  roles: { student: "تلميذ", tutor: "أستاذ", guardian: "وليّ", admin: "أدمين" },
  verif: {
    badge: "موثّق",
    draftTitle: "وثّق حسابك باش تولّي على الخط",
    draftBody: "صفحتك ما زالت مش ظاهرة. زيد بطاقة تعريفك (الشهائد اختيارية) باش تتوثّق وتظهر في اكتشف.",
    draftCta: "وثّق حسابي",
    pendingTitle: "التوثيق في الطريق",
    pendingBody: "قاعدين نتثبّتو في وثائقك. صفحتك تولّي على الخط كي تتقبل (عادة 24–48 ساعة).",
    rejectedTitle: "التوثيق مرفوض",
    rejectedBody: "فمّا مشكل في وثائقك — صلّح وعاود ابعث.",
    rejectedCta: "عاود ابعث وثائقي",
    verifiedTitle: "الحساب موثّق ✓",
    verifiedBody: "صفحتك على الخط وظاهرة في اكتشف.",
  },
  tools: {
    section: "أدوات الحصة",
    join: "ادخل للفيديو",
    whiteboard: "السبورة",
    quiz: "ابدا الكويز",
    replay: "عاود شوف التسجيل",
    none: "ما فماش أدوات مزيودة للحصة هاذي.",
    setLinks: "أدوات الحصة (اختياري)",
    videoUrl: "لينك الفيديو (Jitsi / Meet)",
    whiteboardUrl: "لينك السبورة (Bitpaper / Excalidraw)",
    quizUrl: "لينك الكويز (Wooclap / Quizizz)",
    hint: "حطّ اللينكات متاعك — تلامذتك يحلّوهم بكليكة وقت الحصة.",
  },
  extra: {
    error: "صار مشكل.",
    settings: "الإعدادات",
    notifications: "الإشعارات",
    classPublished: "الحصة تنشرت ✓",
    packPublished: "تنشرت ✓",
    modeEarning: "مع أرباح",
    modeEmpty: "أستاذ جديد",
    demoPreview: "عرض تجريبي",
    searchPh: "لوّج على أستاذ ولا مادة…",
    featured: "أساتذة مؤكّدين",
    noResults: "ما لقيناش أستاذ",
    allSubjects: "الكل",
    comingSoon: "قريب",
  },
  footer: {
    product: "المنصّة",
    legal: "قانوني",
    help: "مساعدة",
    terms: "شروط الاستعمال",
    privacy: "سياسة الخصوصية",
    contact: "اتصل بينا",
    tagline: "الرابط بين التلامذة التوانسة وأساتذتهم.",
    rights: (y: number) => `© ${y} تنجّم · تونس`,
  },
  err: {
    nfCode: "404",
    nfTitle: "الصفحة هاذي ما موجودةش",
    nfBody: "يمكن الرابط غالط، ولا الصفحة تنحّات. ارجع للرئيسية ولا لوّج على أستاذ.",
    nfHome: "ارجع للرئيسية",
    nfExplore: "لوّج على أستاذ",
    crashTitle: "صار مشكل",
    crashBody: "فمّا خطأ ما كانش متوقّع من عندنا. عاود حاول — وإذا تعاود، اكتبلنا.",
    retry: "عاود حاول",
    home: "الرئيسية",
    ref: "المرجع",
  },
};

export const dict = { fr, ar };
export type Dict = typeof fr;
export const isRTL = (l: Locale) => l === "ar";

/* ═══════════════════════════════════════════════════════════════════════════════
   bilingual() — the same FR/AR parity guarantee, for copy that lives OUTSIDE
   this file.

   THE PROBLEM. The dictionary above is compiler-enforced: `const ar: typeof fr`
   means a key added to fr and forgotten in ar is a build error. But ~17 screens
   carry their own `const copy = { fr: {…}, ar: {…} }` — a plain object literal,
   where the two halves are unrelated types and nothing checks anything. That is
   where most of the free-session, cancellation and pricing copy actually lives,
   i.e. exactly the strings Stage B is about to rewrite.

   A missing AR key there does not fail the build. It renders `undefined` to an
   Arabic-speaking user, or throws if the value was called as a function — on a
   page nobody on the team reads. This closes that hole before new strings land.

   HOW IT WORKS. T is inferred from `fr` ALONE (that is what NoInfer buys) and
   `ar` is then checked against it:

     • a key in fr but not ar   → "Property 'x' is missing in type"
     • a key in ar but not fr   → excess-property error on the literal
     • a plural helper typed (n: number) => string in one and a bare string in
       the other → type error

   Without NoInfer, TypeScript would infer T from both halves and quietly widen to
   whatever they have in common — which is precisely the check we want.

   NOTE the absence of a `const` modifier on T. With `const T` every value would
   infer as a string LITERAL ("Tarifs" rather than string) and each Arabic string
   would then have to equal its French counterpart. Parity of KEYS is the goal;
   parity of values is nonsense.
   ═══════════════════════════════════════════════════════════════════════════════ */
export function bilingual<T extends Record<string, unknown>>(copy: {
  fr: T;
  ar: NoInfer<T>;
}): { fr: T; ar: T } {
  return copy;
}
